name: user_repository
description: "The repo that Handles users."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  rxdart: ^0.28.0
firebase_auth: ^6.0.2
cloud_firestore: ^4.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
